import java.util.concurrent.ConcurrentHashMap

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.16'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.github.ferclager'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.batch:spring-batch-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	compileOnly("org.projectlombok:lombok")
	annotationProcessor("org.projectlombok:lombok")
}

test {
	useJUnitPlatform()
	testLogging.info.showStandardStreams = false

	def outputCache = new ConcurrentHashMap<String, List<String>>()
	def cacheKey = { TestDescriptor td -> "${td.className}#${td.name}".toString() }
	beforeTest { TestDescriptor td -> outputCache.remove(cacheKey(td)) }
	onOutput { TestDescriptor td, TestOutputEvent toe ->
		def lines = outputCache.computeIfAbsent(cacheKey(td)) { k -> new ArrayList<String>() }
		lines.add(toe.getMessage())
		while (lines.size() > 1000) lines.remove(0)
	}
	def colorReset = '\u001B[0m'
	def colorGreen = '\u001B[32m'
	def colorRed = '\u001B[31m'
	afterTest { TestDescriptor td, TestResult tr ->
		def lines = outputCache.remove(cacheKey(td)) ?: []
		def color = (tr.resultType == TestResult.ResultType.SUCCESS) ? colorGreen : (tr.resultType == TestResult.ResultType.FAILURE ? colorRed : colorReset)
		println("- Test result for ${td.className}${td.name}: ${color}${tr.resultType}${colorReset}")
		if (tr.resultType == TestResult.ResultType.FAILURE && !lines.isEmpty()) {
			lines.each { print(" > $it") }
			println()
		}
	}
}

jar {
	enabled = false
}

